import { NextResponse } from 'next/server'
import { Resend } from 'resend'

// Initialize Resend
// In a real production environment, you would use process.env.RESEND_API_KEY
// For this decentralized bridge, if no API key is set, we will mock the email send
const resendApiKey = process.env.RESEND_API_KEY || 're_mock_key_for_local_dev'
const resend = new Resend(resendApiKey)

export async function POST(request: Request) {
    try {
        const body = await request.json()
        const { name, email, walletAddress } = body

        if (!email || !name) {
            return NextResponse.json(
                { error: 'Name and email are required parameters' },
                { status: 400 }
            )
        }

        // Determine the user's status for the email body
        const hasWallet = walletAddress && walletAddress.length > 0

        // Construct the email HTML blueprint
        const htmlContent = `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; background-color: #0f172a; color: #f8fafc; padding: 40px; border-radius: 12px; border: 1px solid #1e293b;">
        <h2 style="color: #38bdf8; margin-bottom: 24px;">Digital Will Protocol: Beneficiary Notice</h2>
        
        <p style="font-size: 16px; line-height: 1.6;">Hello <strong>${name}</strong>,</p>
        
        <p style="font-size: 16px; line-height: 1.6;">
          You have been officially registered as a cryptographic beneficiary on the 
          <strong>LASTWISH (Decentralized Digital Will)</strong>.
        </p>

        <div style="background-color: #1e293b; padding: 20px; border-radius: 8px; margin: 24px 0; border-left: 4px solid #38bdf8;">
          <h3 style="margin-top: 0; color: #94a3b8;">Your Registration Data</h3>
          <p style="margin: 8px 0;"><strong>Name:</strong> ${name}</p>
          <p style="margin: 8px 0;"><strong>Email:</strong> ${email}</p>
          <p style="margin: 8px 0;"><strong>Active Web3 Wallet:</strong> ${hasWallet ? `<span style="font-family: monospace; color: #10b981;">${walletAddress}</span>` : '<span style="color: #f59e0b;">Pending Setup</span>'}</p>
        </div>

        ${!hasWallet ? `
        <div style="background-color: rgba(245, 158, 11, 0.1); border: 1px solid rgba(245, 158, 11, 0.3); padding: 16px; border-radius: 8px; margin-bottom: 24px;">
          <p style="color: #fcd34d; margin: 0; font-weight: bold;">⚠️ Action Required: Web3 Wallet Setup</p>
          <p style="margin-top: 8px; font-size: 14px; line-height: 1.5;">
            You currently do not have a wallet attached to this legacy inheritance. 
            To receive digital assets when the protocol triggers, please install <a href="https://metamask.io" style="color: #60a5fa;">MetaMask</a> 
            and link your new 0x... address to our platform using this email.
          </p>
        </div>
        ` : `
        <p style="font-size: 16px; line-height: 1.6;">
          ✅ Your wallet is successfully linked. Should the primary vault owner become inactive, 
          the protocol's Smart Contract will autonomously transfer the allocated blockchain assets and 
          IPFS decryption keys directly to your wallet address.
        </p>
        `}

        <p style="font-size: 14px; color: #64748b; margin-top: 32px; border-top: 1px solid #1e293b; padding-top: 16px;">
          This is an automated operational notification generated by the decentralized Ethereum node. Do not reply.
        </p>
      </div>
    `

        // MOCK SEND if we are missing a real API key to prevent crashing local dev
        if (resendApiKey === 're_mock_key_for_local_dev') {
            console.log('📬 [MOCK EMAIL DISPATCHED via Next.js Bridge]')
            console.log(`To: ${email}`)
            console.log(`Subject: Important: You have been added as a Digital Will Beneficiary`)
            console.log('Status: Success (Simulated)')

            // Simulate network wait
            await new Promise(resolve => setTimeout(resolve, 800))

            return NextResponse.json({
                success: true,
                message: 'Mock email sent successfully',
                mocked: true
            })
        }

        // REAL SEND if RESEND_API_KEY is configured in .env.local
        const data = await resend.emails.send({
            from: 'LASTWISH <onboarding@resend.dev>', // Free tier uses resend.dev testing domain
            to: email,
            subject: 'Important: You have been added as a Digital Will Beneficiary',
            html: htmlContent,
        })

        return NextResponse.json({ success: true, data })

    } catch (error) {
        console.error('Email API Error:', error)
        return NextResponse.json(
            { error: 'Failed to dispatch email bridge execution' },
            { status: 500 }
        )
    }
}
